<a href="https://colab.research.google.com/github/Faiz-Nadeem/DSAPython-20sw039/blob/main/20sw39_lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

20sw039 lab 4

task # 01

In [1]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


task # 02

In [ ]:
import numpy as np

X = np.arange(1, 26).reshape(5, 5)

Y = X[X % 2 != 0]

print("Original Array:")
print(X)
print("\nArray with Odd Numbers:")
print(Y)

task # 03

In [ ]:
import numpy as np

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

task # 04

In [3]:
from google.colab import drive
drive.mount('/NumPy.ipnyb')
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.09403071 -0.56645483 -1.10448936 ...  1.18962792 -1.11278349
   1.45468994]
 [ 0.17258126  0.27089023  1.35284679 ... -0.25322996  0.00457297
   1.36963236]
 [-0.44372089  0.53693631  1.12100965 ... -0.14256416  1.01432212
  -0.41517099]
 ...
 [-0.75742424 -0.96412371 -1.4814827  ... -1.68838327 -0.61535345
  -0.8531121 ]
 [ 1.33092393  1.17754728 -0.50666598 ... -0.38350742 -1.07014663
   0.25826013]
 [-1.05655288 -1.54662462  1.41476176 ...  0.52493271 -0.61738377
   0.00730511]]
Average of all values in X_norm: -1.1368683772161604e-17
Average of minimum values in each column of X_norm: -1.7195072771436533
Average of maximum values in each column of X_norm: 1.7491282243758939
Random permutation of row indices: [459 359 937 430 265 544 960 437 639 837 440 370 135  69 885 402 271 910
 191 739  65 931 800  54 356 631  97 384 510 279 211  37   1 702  39 455
 712 737 974 970 358 10